FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y libssl1.0.0 libssl-dev libgssapi-krb5-2 wget
RUN wget https://info-mongodb-com.s3.amazonaws.com/mongodb-bi/v2/mongodb-bi-linux-x86_64-ubuntu1804-v2.13.1.tgz
RUN mv mongodb-bi-linux-x86_64-ubuntu1804-v2.13.1.tgz mongodb-bi.tgz
RUN tar -xvzf mongodb-bi.tgz
RUN mv mongodb-bi-linux-x86_64-ubuntu1804-v2.13.1 mongodb-bi

WORKDIR /mongodb-bi

RUN mkdir /logs
RUN touch /logs/mongosqld.log
RUN ls
RUN echo $PATH
RUN install -m755 bin/mongo* /usr/local/bin/

EXPOSE 3307

ENTRYPOINT [ "mongosqld", "--config=/mongosqld.conf", "-v" ]
# ENTRYPOINT [ "./init.sh" ]